In [1]:
import numpy as np
from datascience import *

%matplotlib inline
import matplotlib.pyplot as plots
plots.style.use('fivethirtyeight')

(back to slides)
# Random Selection

In [2]:
groups = make_array('treatment', 'control')
groups

array(['treatment', 'control'], dtype='<U9')

Let's randomly assign 1 individual to each group

In [8]:
np.random.choice(groups)

'treatment'

In [10]:
np.random.choice(groups, 1)

array(['treatment'], dtype='<U9')

Let's randomly assign 5 individuals to each group

In [12]:
np.random.choice(groups, 5)

array(['treatment', 'treatment', 'treatment', 'treatment', 'control'],
      dtype='<U9')

How many individuals will recevie the treatment?

In [13]:
np.random.choice(groups, 5)

array(['treatment', 'treatment', 'treatment', 'control', 'treatment'],
      dtype='<U9')

In [15]:
np.random.choice(groups, 5) == "treatment"

array([False, False,  True,  True, False])

In [21]:
sum(np.random.choice(groups, 5) == "treatment")

3

In [23]:
np.count_nonzero(np.random.choice(groups, 5) == "treatment")

5

In [25]:
assignments = np.random.choice(groups, 5)
assignments

array(['treatment', 'treatment', 'treatment', 'treatment', 'control'],
      dtype='<U9')

In [26]:
np.count_nonzero(assignments == "treatment")

4

In [27]:
sum(assignments == "treatment")

4

How many individuals are we adding to our control & treatment groups?

In [28]:
assignments = np.random.choice(groups, 10)
assignments == 'treatment', assignments

(array([False, False,  True, False, False, False,  True, False,  True,
         True]),
 array(['control', 'control', 'treatment', 'control', 'control', 'control',
        'treatment', 'control', 'treatment', 'treatment'], dtype='<U9'))

In [29]:
Table().with_columns('assignments', assignments == 'treatment').where('assignments', True).num_rows

4

In [ ]:
sum(assignments == 'treatment')

In [ ]:
sum(make_array(True, False, False, True))

Let's repeat this

In [30]:
assignments = np.random.choice(groups, 10)
assignments

array(['control', 'control', 'treatment', 'treatment', 'treatment',
       'control', 'treatment', 'treatment', 'control', 'control'],
      dtype='<U9')

Do we see any differences if we run this again??

In [31]:
assignments_one = np.random.choice(groups, 10)
assignments_one

array(['treatment', 'treatment', 'control', 'control', 'treatment',
       'control', 'control', 'treatment', 'control', 'control'],
      dtype='<U9')

Why did we see those differences?

In [ ]:
np.random.choice(groups), groups

In [41]:
control = make_array()
treatment = make_array()
control, treatment

(array([], dtype=float64), array([], dtype=float64))

In [33]:
individual = "Adam"
individual

'Adam'

In [36]:
np.random.choice(groups)

'control'

In [37]:
# use conditionals to determine where to add Adam

In [42]:
if np.random.choice(groups) == "control":
    # lets add Adam to the control group
    control = make_array(individual)
else:
    # lets add Adam to the treatment group
    treatment = make_array(individual)
control, treatment

(array(['Adam'], dtype='<U4'), array([], dtype=float64))

back to slides
# Appending arrays: `np.append()`

Adding an individual to a control or treament group

In [44]:
roster = make_array("Mei", "Adam", "Lara")
roster

array(['Mei', 'Adam', 'Lara'], dtype='<U4')

In [47]:
np.append(roster, "Dereck")

array(['Mei', 'Adam', 'Lara', 'Dereck'], dtype='<U6')

In [48]:
roster

array(['Mei', 'Adam', 'Lara'], dtype='<U4')

In [49]:
new_roster = np.append(roster, "Dereck")

In [51]:
new_roster

array(['Mei', 'Adam', 'Lara', 'Dereck'], dtype='<U6')

back to arrays and RCTs

In [52]:
# Make an empty array for the control and treatment groups
control_group = make_array()
treatment_group = make_array()
control_group, treatment_group
len(control_group)

0

Now let's randomly assign an individual to a group and then add the individual to the corresponding group based on the random assignment

In [54]:
individual = "Joseph"
if np.random.choice(groups) == "control":
    # lets add Joseph to the control group
    # append the individual to the group
    control_group = np.append(control_group, individual)
else:
    # lets add Joseph to the treatment group
    #treatment = make_array(individual)
    treatment_group = np.append(treatment_group, individual)

control_group, treatment_group

(array([], dtype=float64), array(['Joseph'], dtype='<U32'))

Let's add 10 more people to our groups

In [55]:
individual = 1
if np.random.choice(groups) == "control":
    # lets add person 1 to the control group
    # append the individual to the group
    control_group = np.append(control_group, individual)
else:
    # lets add person 1 to the treatment group
    #treatment = make_array(individual)
    treatment_group = np.append(treatment_group, individual)

control_group, treatment_group

(array([1.]), array(['Joseph'], dtype='<U32'))

In [56]:
individual = 2
if np.random.choice(groups) == "control":
    # lets add person 1 to the control group
    # append the individual to the group
    control_group = np.append(control_group, individual)
else:
    # lets add person 1 to the treatment group
    #treatment = make_array(individual)
    treatment_group = np.append(treatment_group, individual)

control_group, treatment_group

(array([1.]), array(['Joseph', '2'], dtype='<U32'))

In [57]:
individual = 3
if np.random.choice(groups) == "control":
    # lets add person 1 to the control group
    # append the individual to the group
    control_group = np.append(control_group, individual)
else:
    # lets add person 1 to the treatment group
    #treatment = make_array(individual)
    treatment_group = np.append(treatment_group, individual)

control_group, treatment_group

(array([1., 3.]), array(['Joseph', '2'], dtype='<U32'))

In [58]:
# lets make a function for adding individuals

In [90]:
def random_assignment(individual, control_groups, treatment_groups):
    """
    randomly assign an individual to control or treatment group
    arguments: 
    returns: 2 arrays: control group, treatment group
    """
    
    groups = make_array("control", "treatment")
    if np.random.choice(groups) == "control":
        # lets add person 1 to the control group
        # append the individual to the group
        control_groups = np.append(control_groups, individual)
    else:
        # lets add person 1 to the treatment group
        #treatment = make_array(individual)
        treatment_groups = np.append(treatment_groups, individual)
    
    return control_groups, treatment_groups
    

In [63]:
control_group = make_array()
treatment_group = make_array()
control_group, treatment_group

(array([], dtype=float64), array([], dtype=float64))

In [69]:
random_assignment("Katherine!", control_group, treatment_group)

(array(['Katherine!'], dtype='<U32'), array([], dtype=float64))

In [70]:
control_group, treatment_group

(array([], dtype=float64), array([], dtype=float64))

### returns and functions review

In [72]:
def add_one(x):
    return x + 1

In [80]:
y = 12
y_plus_one = add_one(y)

In [81]:
y_plus_one

13

In [83]:
def add_one_times2(x):
    add_one = x + 1
    times_two = x * 2
    return add_one, times_two

In [85]:
y = 50
add_one_times2(y)

(51, 100)

In [86]:
result1, result2 = add_one_times2(y)
result1, result2

(51, 100)

### keeping track of random assignments

In [82]:
random_assignment("Katherine!", control_group, treatment_group)

(array([], dtype=float64), array(['Katherine!'], dtype='<U32'))

In [87]:
help(random_assignment)

Help on function random_assignment in module __main__:

random_assignment(individual, control_groups, treatment_groups)
    randomly assign an individual to control or treatment group
    arguments: 
    returns: treatment and control groups as arrays



In [88]:
control_group, treatment_group = random_assignment("Katherine!", control_group, treatment_group)
control_group, treatment_group

(array([], dtype=float64), array(['Katherine!'], dtype='<U32'))

In [91]:
control_group, treatment_group = random_assignment("Madeline!", control_group, treatment_group)
control_group, treatment_group

(array([], dtype=float64), array(['Katherine!', 'Madeline!'], dtype='<U32'))

In [92]:
control_group, treatment_group = random_assignment("Allyce!", control_group, treatment_group)
control_group, treatment_group

(array([], dtype=float64),
 array(['Katherine!', 'Madeline!', 'Allyce!'], dtype='<U32'))

In [93]:
control_group, treatment_group = random_assignment("Jonathan!", control_group, treatment_group)
control_group, treatment_group

(array([], dtype=float64),
 array(['Katherine!', 'Madeline!', 'Allyce!', 'Jonathan!'], dtype='<U32'))

In [94]:
control_group, treatment_group = random_assignment("Isobel", control_group, treatment_group)
control_group, treatment_group

(array(['Isobel'], dtype='<U32'),
 array(['Katherine!', 'Madeline!', 'Allyce!', 'Jonathan!'], dtype='<U32'))

In [95]:
control_group, treatment_group = random_assignment("Christina", control_group, treatment_group)
control_group, treatment_group

(array(['Isobel'], dtype='<U32'),
 array(['Katherine!', 'Madeline!', 'Allyce!', 'Jonathan!', 'Christina'],
       dtype='<U32'))

In [ ]:
groups

In [ ]:
np.append(treatment_group, 1)

In [ ]:
#treatment_group = np.append(treatment_group, 1)
#treatment_group

In [ ]:
control_group = make_array()
treatment_group = make_array()
assigned_group =  np.random.choice(groups)
individual = "individual 1"
print(assigned_group)
if assigned_group == 'treatment':
    treatment_group = np.append(treatment_group, individual)
else:
    control_group = np.append(control_group, individual)

control_group, treatment_group

#### Let's put this control statment into a function:
- What should we name the function? 
- What are the arguments/parameters of the function?
- What should the function return?

In [ ]:
def add_individual_to_group(treatment_group, control_group, individual):
    assigned_group =  np.random.choice(groups)
    print(assigned_group)
    if assigned_group == 'treatment':
        treatment_group = np.append(treatment_group, individual)
    else:
        control_group = np.append(control_group, individual)
    return treatment_group, control_group

Now let's call this function 5 times to assign 5 individuals to the different groups

In [ ]:
control_group = make_array()
treatment_group = make_array()
treatment_group, control_group = add_individual_to_group(treatment_group, control_group, 0)
treatment_group, control_group

In [ ]:
treatment_group, control_group = add_individual_to_group(treatment_group, control_group, 1)
treatment_group, control_group

In [ ]:
treatment_group, control_group = add_individual_to_group(treatment_group, control_group, 2)
treatment_group, control_group

In [ ]:
treatment_group, control_group = add_individual_to_group(treatment_group, control_group, 3)
treatment_group, control_group

We will now see a cleaner way to assign 5 individuals to the different groups
(back to slides)
# `For` Statements

In [96]:
# wednesday section
students = make_array("Temima", "Reda", "Claire", "Matthew", "Obi", "Sophia", "Beatrice", "Fina")
students

array(['Temima', 'Reda', 'Claire', 'Matthew', 'Obi', 'Sophia', 'Beatrice',
       'Fina'], dtype='<U8')

In [97]:
# friday section
students_two = make_array("Steely", "Joseph", "Jonathan")
students_two

array(['Steely', 'Joseph', 'Jonathan'], dtype='<U8')

I want a an array of everyone in the class

In [98]:
np.append("students", "students_two")

array(['students', 'students_two'], dtype='<U12')

In [99]:
np.append(students, students_two)

array(['Temima', 'Reda', 'Claire', 'Matthew', 'Obi', 'Sophia', 'Beatrice',
       'Fina', 'Steely', 'Joseph', 'Jonathan'], dtype='<U8')

In [100]:
np.append(students_two, students)

array(['Steely', 'Joseph', 'Jonathan', 'Temima', 'Reda', 'Claire',
       'Matthew', 'Obi', 'Sophia', 'Beatrice', 'Fina'], dtype='<U8')

In [101]:
class_roster = np.append(students_two, students)
class_roster

array(['Steely', 'Joseph', 'Jonathan', 'Temima', 'Reda', 'Claire',
       'Matthew', 'Obi', 'Sophia', 'Beatrice', 'Fina'], dtype='<U8')

add students one at a time

In [104]:
students_two

array(['Steely', 'Joseph', 'Jonathan'], dtype='<U8')

In [105]:
for student in students_two:
    print(student)


Steely
Joseph
Jonathan


iterate through class roster for random assignment

In [106]:
for student in class_roster:
    print(student)

Steely
Joseph
Jonathan
Temima
Reda
Claire
Matthew
Obi
Sophia
Beatrice
Fina


In [110]:
treatment_group, control_group = random_assignment(treatment_group, control_group, 3)
treatment_group, control_group
treatment_group = make_array()
control_group = make_array()

In [113]:
treatment_group = make_array()
control_group = make_array()
for student in class_roster:
    treatment_group, control_group =  random_assignment(treatment_group, control_group, student)

In [114]:
treatment_group, control_group

(array(['Beatrice', 'Obi', 'Sophia', 'Matthew', 'Reda', 'Temima', 'Joseph',
        'Steely', 'Jonathan', 'Claire'], dtype='<U32'),
 'Fina')

In [ ]:
for i in np.arange(4):
    print('iteration', i)

In [ ]:
print('iteration', 0)
print('iteration', 1)
print('iteration', 2)
print('iteration', 3)

In [ ]:
for i in np.arange(1,10,2):
    print('iteration', i)

In [ ]:
np.arange(1,10,2)

Use a `for` loop to assign the individuals to the different groups

In [ ]:
treatment_group = make_array()
control_group = make_array()
#treatment_group, control_group = add_individual_to_group(treatment_group, control_group, 0)

In [ ]:
for individual in np.arange(0,10):
    treatment_group, control_group = add_individual_to_group(treatment_group, control_group, individual)
treatment_group, control_group

# Heads or Tails Experiment

Let's run 10 experiments where we flip a coin 100 times and see how many times we get heads

Before we begin, let's write out all the steps we need to do

*Hint: Lets work inside out, i.e. lets first write code for one experiment*

1. make an array of heads and tails
2. flip a coin randomly (select head or tails at random) 
3. keep track of whether we got heads our tails

In [ ]:
coins = make_array('heads', 'tails')
coins

In [ ]:
np.random.choice(coins, 100) 

In [ ]:
sum(np.random.choice(coins, 100) == 'heads')

In [ ]:
num_heads = make_array()
for i in np.arange(1000):
    num_heads = np.append(num_heads, sum(np.random.choice(coins, 100) == 'heads'))
num_heads

Let's plot the results from the experiments. What type of plot should we use?

How many times did we get 40 through 60 heads? What percentage of our simulations do these represent?

In [ ]:
1. Make our coins options

(back to slides)

# Monty Hall Simulation

Lets make an array of what can be behind each door

In [ ]:
goats = make_array('first goat', 'second goat')
hidden_behind_door = ... # Lets add the car

Let's make a choice. We won't choose a door but rather whats behind the door

In [ ]:
# Remember np.random.choice
contestant_choice = ...
contestant_choice

In [ ]:
def other_goat(a_goat):
    ''' Returns the other goat that wasn't chosen
    '''
    ...
    return ...

Let's test `other_goat()`

What happens next? 
Monty chooses the door to show and we have a remaining door

In [ ]:
monty_choice = ...
remaining_door = ...

But remember, these choices are conditioned on what the contestant chose

In [ ]:
if ...: # one option for contest's choice
    ...
elif ...: # second option for contests's choice
    ...
elif ...: # third option for contestants choice
    ...
    
contestant_choice, monty_choice, remaining_door

Let's add this to a function so that we can run many simulations of the game

In [ ]:
def monty_hall():
    '''
    Simulates one run of monty hall.
    Returns values behind contestant_choice, monty_choice, remaining_door
    '''
    ...
    return 

Now let's play this game once

Let's play it another time

#### Let's play this game multiple times
How could we do that based on what we learned in today's lecture?

### Simulations

Let's make a table where we will keep simulations
We want to keep track of the original guess, what was revealed, and what is remaining in the other hidden door

In [ ]:
games = Table(['Guess', 'Revealed', 'Remaining'])

### How could we see what remains for each guess?
what metho dshould we call on the table?

Let's group on the remaining to decide if we should change?

In [ ]:
# Initialize Otter
import otter
grader = otter.Notebook()
grader.export("Lecture_9_completed.ipynb", pdf=False)