In [1]:
from datascience import *
import numpy as np

%matplotlib inline
import matplotlib.pyplot as plots
plots.style.use('fivethirtyeight')

# Table Questions

**Question 1:** Given a file callled `nba_salaries.csv`, how can we load it into a `Table`?

In [3]:
nba = Table.read_table("nba_salaries.csv")
nba

PLAYER           | POSITION | TEAM          | '15-'16 SALARY
Paul Millsap     | PF       | Atlanta Hawks | 18.6717
Al Horford       | C        | Atlanta Hawks | 12
Tiago Splitter   | C        | Atlanta Hawks | 9.75625
Jeff Teague      | PG       | Atlanta Hawks | 8
Kyle Korver      | SG       | Atlanta Hawks | 5.74648
Thabo Sefolosha  | SF       | Atlanta Hawks | 4
Mike Scott       | PF       | Atlanta Hawks | 3.33333
Kent Bazemore    | SF       | Atlanta Hawks | 2
Dennis Schroder  | PG       | Atlanta Hawks | 1.7634
Tim Hardaway Jr. | SG       | Atlanta Hawks | 1.30452
... (407 rows omitted)

**Question 2:** What are the columns in our table?

In [7]:
nba.labels

('PLAYER', 'POSITION', 'TEAM', "'15-'16 SALARY")

**Question 3**: Find the names of all centers (C) who make more than $15M/year

*Hint:* break this into two steps

In [9]:
# all the centers
nba.where(1, "C")

PLAYER             | POSITION | TEAM              | '15-'16 SALARY
Al Horford         | C        | Atlanta Hawks     | 12
Tiago Splitter     | C        | Atlanta Hawks     | 9.75625
Walter Tavares     | C        | Atlanta Hawks     | 1
Tyler Zeller       | C        | Boston Celtics    | 2.61698
Jared Sullinger    | C        | Boston Celtics    | 2.56926
Kelly Olynyk       | C        | Boston Celtics    | 2.16516
Andrea Bargnani    | C        | Brooklyn Nets     | 1.3629
Al Jefferson       | C        | Charlotte Hornets | 13.5
Cody Zeller        | C        | Charlotte Hornets | 4.2042
Frank Kaminsky III | C        | Charlotte Hornets | 2.61252
... (59 rows omitted)

In [11]:
nba.where("POSITION", "C")

PLAYER             | POSITION | TEAM              | '15-'16 SALARY
Al Horford         | C        | Atlanta Hawks     | 12
Tiago Splitter     | C        | Atlanta Hawks     | 9.75625
Walter Tavares     | C        | Atlanta Hawks     | 1
Tyler Zeller       | C        | Boston Celtics    | 2.61698
Jared Sullinger    | C        | Boston Celtics    | 2.56926
Kelly Olynyk       | C        | Boston Celtics    | 2.16516
Andrea Bargnani    | C        | Brooklyn Nets     | 1.3629
Al Jefferson       | C        | Charlotte Hornets | 13.5
Cody Zeller        | C        | Charlotte Hornets | 4.2042
Frank Kaminsky III | C        | Charlotte Hornets | 2.61252
... (59 rows omitted)

In [13]:
# how many centers are there
nba_centers = nba.where("POSITION", "C")
nba_centers.num_rows

69

In [14]:
# who make more than 15M
nba_centers.where(3, are.above(15000000))

PLAYER | POSITION | TEAM | '15-'16 SALARY

In [15]:
nba_centers.where(3, are.above(15))

PLAYER           | POSITION | TEAM                  | '15-'16 SALARY
Dwight Howard    | C        | Houston Rockets       | 22.3594
Roy Hibbert      | C        | Los Angeles Lakers    | 15.5922
Marc Gasol       | C        | Memphis Grizzlies     | 19.688
Enes Kanter      | C        | Oklahoma City Thunder | 16.4075
DeMarcus Cousins | C        | Sacramento Kings      | 15.852

In [16]:
nba_centers.where(3, are.above(15)).select("PLAYER")

PLAYER
Dwight Howard
Roy Hibbert
Marc Gasol
Enes Kanter
DeMarcus Cousins

**Question 4**: Which player had the highest salary in 2015-16?

*Hint:* how do we access an individual (row) in a Table

In [18]:
nba.show(1)

In [21]:
nba.sort("'15-'16 SALARY", descending=True)

PLAYER          | POSITION | TEAM                  | '15-'16 SALARY
Kobe Bryant     | SF       | Los Angeles Lakers    | 25
Joe Johnson     | SF       | Brooklyn Nets         | 24.8949
LeBron James    | SF       | Cleveland Cavaliers   | 22.9705
Carmelo Anthony | SF       | New York Knicks       | 22.875
Dwight Howard   | C        | Houston Rockets       | 22.3594
Chris Bosh      | PF       | Miami Heat            | 22.1927
Chris Paul      | PG       | Los Angeles Clippers  | 21.4687
Kevin Durant    | SF       | Oklahoma City Thunder | 20.1586
Derrick Rose    | PG       | Chicago Bulls         | 20.0931
Dwyane Wade     | SG       | Miami Heat            | 20
... (407 rows omitted)

In [24]:
nba.sort("'15-'16 SALARY", descending=True).show(1)

In [27]:
nba.sort("'15-'16 SALARY", descending=True).take(0).select("PLAYER")

PLAYER
Kobe Bryant

In [31]:
nba.sort("'15-'16 SALARY", descending=True).select("PLAYER").take(0)

PLAYER
Kobe Bryant

In [ ]:
# skip

In [ ]:
# skip

In [ ]:
# skip

**Question:** What type is returned by `take()`?

In [28]:
type(nba.sort("'15-'16 SALARY", descending=True).take(0))

datascience.tables.Table

In [29]:
nba.labels

('PLAYER', 'POSITION', 'TEAM', "'15-'16 SALARY")

In [33]:
nba.show(5)

In [84]:
nba.sort("'15-'16 SALARY", descending=True).take(0).select("PLAYER")

PLAYER
Kobe Bryant

In [87]:
nba.sort("'15-'16 SALARY", descending=True).column("PLAYER")

array(['Kobe Bryant', 'Joe Johnson', 'LeBron James', 'Carmelo Anthony',
       'Dwight Howard', 'Chris Bosh', 'Chris Paul', 'Kevin Durant',
       'Derrick Rose', 'Dwyane Wade', 'Kevin Love', 'LaMarcus Aldridge',
       'Marc Gasol', 'Blake Griffin', 'Paul Millsap', 'Paul George',
       'Russell Westbrook', 'Kyrie Irving', 'Jimmy Butler', 'Enes Kanter',
       'Kawhi Leonard', 'Tobias Harris', 'DeMarcus Cousins', 'John Wall',
       'James Harden', 'Roy Hibbert', 'Eric Gordon', 'Klay Thompson',
       'David Lee', 'Gordon Hayward', 'Chandler Parsons', 'Goran Dragic',
       'Khris Middleton', 'Tristan Thompson', 'Draymond Green',
       'Danilo Gallinari', 'Reggie Jackson', 'Andrew Bogut',
       'DeMarre Carroll', 'Al Jefferson', 'Eric Bledsoe', 'Tony Parker',
       'Joakim Noah', 'Nicolas Batum', 'Tyson Chandler', 'Nene Hilario',
       'Ricky Rubio', 'Robin Lopez', 'Ty Lawson', 'Rudy Gay',
       'Serge Ibaka', 'Nikola Pekovic', 'Al Horford', 'Kemba Walker',
       'Kyle Lowry', '

In [88]:
nba.sort("'15-'16 SALARY", descending=True).column("PLAYER").item(0)

'Kobe Bryant'

In [89]:
highest_paid_player = nba.sort("'15-'16 SALARY", descending=True).column("PLAYER").item(0)
highest_paid_player

'Kobe Bryant'

In [90]:
nba

PLAYER           | POSITION | TEAM          | '15-'16 SALARY
Paul Millsap     | PF       | Atlanta Hawks | 18.6717
Al Horford       | C        | Atlanta Hawks | 12
Tiago Splitter   | C        | Atlanta Hawks | 9.75625
Jeff Teague      | PG       | Atlanta Hawks | 8
Kyle Korver      | SG       | Atlanta Hawks | 5.74648
Thabo Sefolosha  | SF       | Atlanta Hawks | 4
Mike Scott       | PF       | Atlanta Hawks | 3.33333
Kent Bazemore    | SF       | Atlanta Hawks | 2
Dennis Schroder  | PG       | Atlanta Hawks | 1.7634
Tim Hardaway Jr. | SG       | Atlanta Hawks | 1.30452
... (407 rows omitted)

# Arrays

In [ ]:
 # let's make an array
  # does anyone know how to make an array from the reading?
  # lets make the array be an array of numbers

In [34]:
make_array()

array([], dtype=float64)

In [35]:
make_array(5,6,7)

array([5, 6, 7])

In [37]:
example_array = make_array(5,6,7)
example_array

array([5, 6, 7])

#### lets apply different computations to the array

In [38]:
 # addition
example_array + 1

array([6, 7, 8])

In [39]:
 # multiplication
example_array * 4.5

array([22.5, 27. , 31.5])

In [40]:
 # square
example_array ** 2    

array([25, 36, 49])

In [41]:
  # absolute value 
abs(example_array)

array([5, 6, 7])

In [42]:
  # absolute value 
abs(make_array(-1, -5, 6))

array([1, 5, 6])

In [43]:
make_array("string", 1)

array(['string', '1'], dtype='<U21')

In [44]:
str(1)

'1'

In [45]:
make_array(2, 4.4)

array([2. , 4.4])

In [46]:
make_array(1,2,34)

array([ 1,  2, 34])

In [47]:
aa = make_array(1,2,3,4)
aa

array([1, 2, 3, 4])

In [ ]:
# find the sum of all values in an array

In [50]:
sum(aa)

10

In [ ]:
# find the maximum value in the array

In [48]:
max(aa)

4

In [ ]:
# find the minimum value

In [51]:
min(aa)

1

In [ ]:
# find the first item in an array
# note to Adam (dont use index slicing)

In [52]:
aa

array([1, 2, 3, 4])

In [53]:
aa.select(0)

AttributeError: 'numpy.ndarray' object has no attribute 'select'

In [54]:
aa.item(0)

1

In [55]:
aa

array([1, 2, 3, 4])

In [56]:
len(aa)

4

In [57]:
aa.len()

AttributeError: 'numpy.ndarray' object has no attribute 'len'


# Ranges

In [ ]:
  #np.arrange(end), np.arrange(start, end), step

In [59]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [60]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [61]:
np.arange(10,20,2)

array([10, 12, 14, 16, 18])

In [62]:
np.arange(10,5)

array([], dtype=int64)

In [63]:
np.arange(10,5,-1)

array([10,  9,  8,  7,  6])

## Array statistics using numpy
(look at end of array's in python reference)

In [ ]:
# np.mean, np.average

In [64]:
np.average(np.arange(10,5,-1))

8.0

In [65]:
np.mean(np.arange(10,5,-1))

8.0

In [66]:
np.mean(np.arange(10,5,-1)) ==np.average(np.arange(10,5,-1))

True

In [67]:
# absolute
np.arange(-10, 0)

array([-10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1])

In [68]:
np.abs(np.arange(-10, 0))

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [70]:
# make an empty array and add elements

In [72]:
empty_array = make_array()
empty_array

array([], dtype=float64)

In [73]:
np.append(empty_array, 99)

array([99.])

In [74]:
len(empty_array)

0

In [75]:
updated_array  = np.append(empty_array, 99)
updated_array

array([99.])

In [76]:
len(updated_array)

1

In [79]:
updated_array.item(1)

IndexError: index 1 is out of bounds for axis 0 with size 1

In [80]:
empty_array = np.append(empty_array, 99)
empty_array

array([99.])

In [81]:
len(empty_array)

1

In [82]:
np.append(updated_array, "hello")

array(['99.0', 'hello'], dtype='<U32')

(back to slides)
# Census

In [92]:
data_url = "https://www2.census.gov/programs-surveys/popest/datasets/2010-2015/national/totals/nst-est2015-popchg2010_2015.csv"
census = Table.read_table(data_url)
census

SUMLEV | REGION | DIVISION | STATE | NAME             | ESTIMATESBASE2010 | POPESTIMATE2010 | POPESTIMATE2011 | POPESTIMATE2012 | POPESTIMATE2013 | POPESTIMATE2014 | POPESTIMATE2015 | NPOPCHG_2010 | NPOPCHG_2011 | NPOPCHG_2012 | NPOPCHG_2013 | NPOPCHG_2014 | NPOPCHG_2015 | PPOPCHG_2010 | PPOPCHG_2011 | PPOPCHG_2012 | PPOPCHG_2013 | PPOPCHG_2014 | PPOPCHG_2015 | NRANK_ESTBASE2010 | NRANK_POPEST2010 | NRANK_POPEST2011 | NRANK_POPEST2012 | NRANK_POPEST2013 | NRANK_POPEST2014 | NRANK_POPEST2015 | NRANK_NPCHG2010 | NRANK_NPCHG2011 | NRANK_NPCHG2012 | NRANK_NPCHG2013 | NRANK_NPCHG2014 | NRANK_NPCHG2015 | NRANK_PPCHG2010 | NRANK_PPCHG2011 | NRANK_PPCHG2012 | NRANK_PPCHG2013 | NRANK_PPCHG2014 | NRANK_PPCHG2015
10     | 0      | 0        | 0     | United States    | 308758105         | 309346863       | 311718857       | 314102623       | 316427395       | 318907401       | 321418820       | 588758       | 2371994      | 2383766      | 2324772      | 2480006      | 2511419      | 0.190686     | 0.766775     | 0.764717     | 0.740131     | 0.783752     | 0.787507     | X                 | X                | X                | X                | X                | X                | X                | X               | X               | X               | X               | X               | X               | X               | X               | X               | X               | X               | X
20     | 1      | 0        | 0     | Northeast Region | 55318348          | 55387174        | 55638038        | 55835056        | 56019353        | 56171281        | 56283891        | 68826        | 250864       | 197018       | 184297       | 151928       | 112610       | 0.124418     | 0.452928     | 0.354107     | 0.330074     | 0.271206     | 0.200476     | 4                 | 4                | 4                | 4                | 4                | 4                | 4                | 3               | 3               | 3               | 4               | 4               | 4               | 3               | 3               | 3               | 4               | 4               | 4
20     | 2      | 0        | 0     | Midwest Region   | 66929897          | 66977505        | 67156488        | 67340231        | 67565788        | 67762069        | 67907403        | 47608        | 178983       | 183743       | 225557       | 196281       | 145334       | 0.0711311    | 0.267229     | 0.273604     | 0.334951     | 0.290504     | 0.214477     | 3                 | 3                | 3                | 3                | 3                | 3                | 3                | 4               | 4               | 4               | 3               | 3               | 3               | 4               | 4               | 4               | 3               | 3               | 3
20     | 3      | 0        | 0     | South Region     | 114562953         | 114862858       | 116080267       | 117331340       | 118487418       | 119795010       | 121182847       | 299905       | 1217409      | 1251073      | 1156078      | 1307592      | 1387837      | 0.261782     | 1.05988      | 1.07777      | 0.98531      | 1.10357      | 1.15851      | 1                 | 1                | 1                | 1                | 1                | 1                | 1                | 1               | 1               | 1               | 1               | 1               | 1               | 1               | 1               | 1               | 2               | 2               | 1
20     | 4      | 0        | 0     | West Region      | 71946907          | 72119326        | 72844064        | 73595996        | 74354836        | 75179041        | 76044679        | 172419       | 724738       | 751932       | 758840       | 824205       | 865638       | 0.239648     | 1.00492      | 1.03225      | 1.03109      | 1.10848      | 1.15144      | 2                 | 2                | 2                | 2                | 2                | 2                | 2                

In [93]:
census.num_rows, census.num_columns

(57, 43)

### Difference between `select()` and `column()`

In [94]:
census.column(0)

array([10, 20, 20, 20, 20, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40,
       40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40,
       40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40,
       40, 40, 40, 40, 40, 40])

In [95]:
census.select(0)

SUMLEV
10
20
20
20
20
40
40
40
40
40
... (47 rows omitted)

**Question:** What's the difference between these two?

### Explore data

In [96]:
census.show(5)
census.num_columns, census.num_rows

(43, 57)

## Exploring the Table
If we look at [this documentation](https://www2.census.gov/programs-surveys/popest/datasets/2010-2015/national/totals/nst-est2015-popchg2010-2015.pdf), we can see a description of the table

In [ ]:
# Lets explore a few of the columns

In [97]:
 # "REGION"
# Categorical or Numerical?
census.select("REGION")

REGION
0
1
2
3
4
3
4
4
3
4
... (47 rows omitted)

In [98]:
 # DIVISION
    # Categorical or Numerical?
census.select("DIVISION")

DIVISION
0
0
0
0
0
6
9
8
7
9
... (47 rows omitted)

In [99]:
 # STATE
    # Categorical or Numerical?
census.select("STATE")

STATE
0
0
0
0
0
1
2
4
5
6
... (47 rows omitted)

In [101]:
 # NAME
    # Categorical or Numerical?
census.select("NAME")

NAME
United States
Northeast Region
Midwest Region
South Region
West Region
Alabama
Alaska
Arizona
Arkansas
California
... (47 rows omitted)

In [103]:
census.select("ESTIMATESBASE2010")

ESTIMATESBASE2010
308758105
55318348
66929897
114562953
71946907
4780127
710249
6392307
2915958
37254503
... (47 rows omitted)

## Selecting a few columns of interest

Lets look at the "NAME", "STATE", "REGION", "2013 Estimate", "2014 Estimate"

In [105]:
partial_census = census.select("NAME", "STATE", "REGION", "POPESTIMATE2013", "POPESTIMATE2014")

In [106]:
# Relabel columns
partial_census

NAME             | STATE | REGION | POPESTIMATE2013 | POPESTIMATE2014
United States    | 0     | 0      | 316427395       | 318907401
Northeast Region | 0     | 1      | 56019353        | 56171281
Midwest Region   | 0     | 2      | 67565788        | 67762069
South Region     | 0     | 3      | 118487418       | 119795010
West Region      | 0     | 4      | 74354836        | 75179041
Alabama          | 1     | 3      | 4830533         | 4846411
Alaska           | 2     | 4      | 737442          | 737046
Arizona          | 4     | 4      | 6630799         | 6728783
Arkansas         | 5     | 3      | 2957957         | 2966835
California       | 6     | 4      | 38414128        | 38792291
... (47 rows omitted)

# Column Arithmetic 

Difference between 13 and 13 estimate

In [ ]:
change = ...
change

## Make new table with change

In [ ]:

# Hint, use with_columns

### Reformatter

In [ ]:
## Reformat these changes
# NumberFormatter, PercentFormatter
# set_format

### Interpretting these changes

**Are these changes meaningful?**

In [ ]:
 # Convert changes to percentages

In [ ]:
# Let's look at larger ranges in time, we might see more changes then

# Analyzing the results/table

In [ ]:
# find the regiion with the largest total change

In [ ]:
# demonstrate rows

In [ ]:
# find the regiion with the largest percentage change

In [ ]:
# add anual growth based on total growth